-- Create a table to store results
CREATE TABLE files (line STRING);

-- Load data into the database using a file on your local system (NOT HDFS)
LOAD DATA LOCAL INPATH '/root/input.txt' INTO TABLE files;

-- Create a new table using data from the files table
CREATE TABLE word_counts AS
SELECT word, count(1) AS count FROM
(SELECT explode(split(line, ' ')) AS word FROM files) AS w
GROUP BY word
ORDER BY word;

-- To view the final result
SELECT * FROM word_counts;
