---
- hosts: all
  become: yes # Become sudo
  tasks:
      - name: Create the wheel group
        group:
            name: wheel
            state: present
      - name: Create a user
        user:
            name: testuser
            groups: wheel
            append: true