---
- hosts: local
  become: True
  tasks:
    - name: Install required components
      apt:
        name: 
          - git
          - maven
          - openjdk-17-jdk
        state: present
    - name: clone maven repo
      git:
        repo: https://github.com/training-support/FST_JUnit_Project.git
        dest: /home/chitra266/FST_JUnit_Project
    - name: Run maven tests
      command: mvn clean test
      args:
        chdir: /home/chitra266/FST_JUnit_Project
